name=int(input("no days employee1 work"))
print("no days hour" , name)
name1=int(input("no of hour employee1 work in first day"))
print("no days hour" , name1)
name2=int(input("no days hour employee1 work in second day"))
print("no days hour" , name2)
name3=int(input("no hour employee1 work in third day"))
print("no days hour" , name3)
print("you have work", name1+name2+name3, "hour")
print("your average work", ((name1+name2+name3)/3), "in total days")